### ISSUE TITLE
RFE: Allow filtering out minion-specific metrics via a cmdline option

### ISSUE THREAD

**Issue by rjel2159** [kpetremann/salt-exporter#20]
Can you please add a cmdline option that filters out/disables all minion-specific metrics?  This is needed to avoid having high-cardinality labels in Prometheus with masters that have a large number (1k+) of minions connecting to them.
Setting the '-health-minions' option to false doesn't work as I still see the following metrics:

```
    salt_responses_total(minion="XXXX", success=true) = <count>

**Comment by kpetremann** [comment]
Hello @rjel2159,

Thanks for submitting the issue.

`-health-minions` was introduced recently and only concerns `salt_function_status` metric.

I'll look into your request, I just wonder what would be the best approach: to create an a new flag, or make `health-minions` manage the `salt_responses_total` as well.

**Comment by kpetremann** [comment]
@rjel2159 done in v0.5.0
