### ISSUE TITLE
No salt_function_status() metrics except for highstate regardless of the -health-states-filter option passed

### ISSUE THREAD

**Issue by rjel2159** [kpetremann/salt-exporter#21]
I've tried to use the example from README, but it doesn't seem to be working in version 0.4.0, i.e.:

    ./salt-exporter -health-states-filter=test.ping,state.apply -health-functions-filter=""

But running 'salt-call test.ping' against the master with the above cmdline option doesn't seem to produce the below metric:

```
   salt_function_status{function="test.ping",minion="<minion>",state=""} 1

**Comment by kpetremann** [comment]
Hi @rjel2159,

Thanks for reporting this.

There is a mistake in the documentation.
`test.ping` and `state.apply` are functions not state.

The right command is:
```./salt-exporter -health-functions-filter=test.ping,state.apply -health-states-filter=""```

**Comment by kpetremann** [comment]
doc updated.

**Comment by rjel2159** [comment]
Thanks for your quick reply. Yes, this works, but how does one include all sls states into the filter? Wildcards don't seem to work, I see the following but no salt_function_status() metric, i.e.:

```
./salt-exporter -health-functions-filter="state.sls" -health-states-filter="sys.*"


```
salt_function_responses_total{function="state.sls",state="sys.passwd",success="true"} 1
salt_responses_total{minion="XXX",success="true"} 1

**Comment by kpetremann** [comment]
Wildcards/all is currently not supported.

Implementation is a simple AND filter: an event must match both functions-filter and states-filter.
For instance, you cannot watch `test.ping` and `state.sls test` at the same time.

I can work on this, but this could make cardinality rapidly explode as the metric is per minion and function/state.

**Comment by rjel2159** [comment]
Thanks, I think it'd useful to allow getting metrics for all functions via a wildcard when explicitly turned on by the cmdline option.

**Comment by kpetremann** [comment]
@rjel2159 done in v0.5.0
