### ISSUE TITLE
please add -version  switch

### ISSUE THREAD

**Issue by jacekjaros** [kpetremann/salt-exporter#45]
hi,

please add -version switch
for now only option to determinate version is to run exporter (then version is print to output) which could be hard to use in eg. shell scripts.

thanks,

**Comment by kpetremann** [comment]
Hi @jacekjaros
Sure I'll add it in the next release

**Comment by kpetremann** [comment]
done!

```
salt-exporter --version
Version: 0.8.0
Build date: 2023-07-19T20:43:22Z
Commit: fe1005a649f7db0f69353775f10deb811ee8e30e
```
