### ISSUE TITLE
[salt-exporter] Run the `salt-call state.apply` command from minion without metrics

### ISSUE THREAD

**Issue by cccfs** [kpetremann/salt-exporter#56]

**Comment by kpetremann** [comment]
hello @cccfs,

I tested in a clean environment (docker compose used for end to end tests) and I do see metrics with the default configuration:
```
$ docker compose exec minion salt-call state.apply
$ curl -s 127.0.0.1:2112/metrics | grep salt_ | grep -v "#"
salt_function_responses_total{function="state.apply",state="highstate",success="false"} 1
salt_responses_total{minion="foo",success="false"} 1
```

Could you please provide more details, like the metrics you have and the metric you are expecting/missing?

Thanks

**Comment by kpetremann** [comment]
closing this ticket.
If you still have the issue, feel free to re-open it, but please provide details.
