### ISSUE TITLE
Feature: Grafana dashboard

### ISSUE THREAD

**Issue by oijkn** [kpetremann/salt-exporter#6]
Hello, can you provide us a Grafana Dashboard, please ?

**Comment by kpetremann** [comment]
Hi @oijkn,
Here you go. A first simple dashboard. This can be improved, but I think it is a good start.
Please let me know if it is ok for you (see the attached PR).

**Comment by oijkn** [comment]
Thank you for this first dashboard. Can you do something like that https://gitlab.com/turtletraction-oss/salt-grafana/-/raw/main/docs/_static/dashboard-overview.png ?

**Comment by kpetremann** [comment]
it is not doable as the exporter does not keep the start date and time. Closing this issue. Thanks
